title: "Mon portfolio"
description: "Photographie, poèmes, pitchs et vidéos par marskircher"
remote_theme: "mmistakes/minimal-mistakes"
locale: "fr-FR"
navigation:
  - title: "Accueil"
    url: "/"
  - title: "À propos"
    url: "/about/"
  - title: "Boutique"
    url: "/boutique/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"